numerical_threshold: 1e-6
statistical_threshold: 0
maximum_added_neurons: null
dtype: torch.float32
compute_delta: False
use_covariance: True
alpha_zero: False
omega_zero: False
use_projection: True
ignore_singular_values: False
